var compression = require('compression')
var express = require('express')
var path = require('path')
var favicon = require('serve-favicon')
var logger = require('morgan')
var cookieParser = require('cookie-parser')
var bodyParser = require('body-parser')
var errorHandler = require('./middleware/error-handler')
var error404 = require('./middleware/error404')

var index = require('./routes/index')
var registers = require('./routes/registers')
var devices = require('./routes/devices')

var app = express()
app.use(compression())
   .use(favicon(path.join(__dirname, 'public', 'favicon.ico')))
   .use(logger('dev'))
   .use(bodyParser.json())
   .use(bodyParser.urlencoded({ extended: false }))
   .use(cookieParser())
   .use(express.static(path.join(__dirname, 'public')))
   .use('/', index)
   .use('/api', registers)
   .use('/devices', devices)
   .use(error404)
   .use(errorHandler)

module.exports = app
